services:
  db:
    image: mariadb:latest
    container_name: tasks-mariadb
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tasks
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - task_network
  backend:
    build:
      context: "../../spring_tasks"
      dockerfile: Dockerfile
    container_name: tasks-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/tasks
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      APP_ADMIN_EMAIL: ${APP_ADMIN_EMAIL}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - task_network
  frontend:
    container_name: tasks-vue-frontend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:80"
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - task_network
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:stable-alpine
    volumes:
      - ./nginx-proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - task_network

networks:
  task_network:
    driver: bridge

volumes:
  mariadb_data: