services:
    db:
        image: mariadb:latest
        container_name: tasks-mariadb
        restart: always
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: tasks
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - task_network
    backend:
        build:
            context: "../../spring_tasks"
            dockerfile: Dockerfile
        container_name: tasks-backend
        environment:
            SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/tasks
            SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
            SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            -   db
        ports:
            - "8088:8088"
        networks:
            - task_network
    frontend:
        container_name: tasks-vue-frontend
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            -   backend
        ports:
            - "5173:80"
        networks:
            - task_network
    nginx-proxy:
        container_name: nginx-proxy
        image: nginx:stable-alpine
        volumes:
            - ./nginx-proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - backend
            - frontend
        networks:
            - task_network

networks:
    task_network:
        driver: bridge

volumes:
    mariadb_data: